/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lpsconnect;

import com.mysql.jdbc.Connection;
import java.sql.Blob;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sankalp
 */
public class userFinal extends javax.swing.JFrame {

    /**
     * Creates new form userFinal
     */
    public userFinal() {
        initComponents();
        jMenu3.setEnabled(false);
        jMenu3.setText(new java.util.Date().toString());
        Date.setText(new java.util.Date().toString());
        Date.setVisible(false);
        FinalName.setVisible(false);
        FinalName2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel5.setVisible(false);
        jLabel10.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        FinalEmail.setVisible(false);
        FinalHobby.setVisible(false);
        FinalIntrest.setVisible(false);
        FinalJoin.setVisible(false);
        FinalPhoto.setVisible(false);
        FinalIntrest.setVisible(false);
        FinalRelation.setVisible(false);
        jButton9.setVisible(false);
        jButton8.setVisible(false);
        jMenu1.setEnabled(false);
        jMenu2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        delemail = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JPasswordField();
        Chat = new javax.swing.JFrame();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Detail = new javax.swing.JButton();
        Date = new javax.swing.JLabel();
        sent = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jLabel8 = new javax.swing.JLabel();
        FinalName2 = new javax.swing.JLabel();
        FinalName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FinalEmail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FinalHobby = new javax.swing.JLabel();
        FinalIntrest = new javax.swing.JLabel();
        FinalRelation = new javax.swing.JLabel();
        FinalJoin = new javax.swing.JLabel();
        FinalPhoto = new javax.swing.JPanel();
        FinalPhoto1 = new javax.swing.JLabel();
        FPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        passcheck = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setBounds(new java.awt.Rectangle(319, 139, 319, 139));
        jDialog2.setMinimumSize(new java.awt.Dimension(325, 150));
        jDialog2.setUndecorated(true);

        jLabel4.setText("Old Password");

        jLabel6.setText("New Password");

        jButton6.setText("Change Passowrd");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.setText("jPasswordField1");

        jTextField2.setText("jPasswordField2");

        jTextField4.setText("jPasswordField1");

        jLabel7.setText("Confirm New Password");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1))))
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel11.setText("Re-Enter Password");

        delemail.setText("<email>");

        jButton5.setText("Confirm Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Optional)", "Many Glitches", "Will Return In Future", "Personal Reason" }));

        jLabel12.setText("Reason");

        jTextField3.setText("jPasswordField1");

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton5))
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delemail)
                        .addGap(27, 27, 27)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delemail)
                    .addComponent(jLabel11)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        Chat.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Chat.setTitle("Chat sCool Session");
        Chat.setMaximumSize(new java.awt.Dimension(877, 619));
        Chat.setMinimumSize(new java.awt.Dimension(857, 619));
        Chat.setPreferredSize(new java.awt.Dimension(687, 569));

        jLabel15.setText("Message");

        jButton15.setText("Send");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel16.setText("To (E-Mail)");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sent To", "On"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton17.setText("Clear History");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jButton17)
                .addContainerGap(355, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(jButton17))
        );

        jTabbedPane4.addTab("Sent Messages", jPanel1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Recieved Msg", "Sent By", "On", "Sender Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton10.setText("Clear History");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton10))
        );

        jTabbedPane4.addTab("Recieved Messages", jPanel3);

        jButton18.setText("Close Session");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        Detail.setText("Refresh");
        Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailActionPerformed(evt);
            }
        });

        sent.setForeground(new java.awt.Color(102, 0, 102));
        sent.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Online Now");

        jTable1.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTable1.setRowSelectionAllowed(false);
        jScrollPane4.setViewportView(jTable1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show Online ON", "Show Online OFF" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        Chat.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout ChatLayout = new javax.swing.GroupLayout(Chat.getContentPane());
        Chat.getContentPane().setLayout(ChatLayout);
        ChatLayout.setHorizontalGroup(
            ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChatLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChatLayout.createSequentialGroup()
                        .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChatLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(ChatLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(460, 460, 460))
                            .addGroup(ChatLayout.createSequentialGroup()
                                .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ChatLayout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jButton15)
                                        .addGap(125, 125, 125)
                                        .addComponent(Detail)
                                        .addGap(130, 130, 130)
                                        .addComponent(jButton18))
                                    .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        ChatLayout.setVerticalGroup(
            ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChatLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ChatLayout.createSequentialGroup()
                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(19, 19, 19)
                        .addGroup(ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15)
                            .addComponent(jButton18)
                            .addComponent(Detail))
                        .addGap(18, 18, 18)
                        .addComponent(sent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Your Account");

        jLabel8.setText("E-Mail");

        FinalName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FinalName2.setText("<Last_Name>");

        FinalName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FinalName.setText("<First_Name>");

        jLabel1.setText("Intrested In");

        jLabel5.setText("Class-Section/Alumni");

        jLabel10.setText("Year Of Joining");

        jLabel9.setText("Hobbies");

        FinalEmail.setText("<e_mail>");

        FinalHobby.setText("<hobbies>");

        FinalIntrest.setText("<Intrest>");

        FinalRelation.setText("<Relate_Status>");

        FinalJoin.setText("<Join>");

        FinalPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout FinalPhotoLayout = new javax.swing.GroupLayout(FinalPhoto);
        FinalPhoto.setLayout(FinalPhotoLayout);
        FinalPhotoLayout.setHorizontalGroup(
            FinalPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalPhotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FinalPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FinalPhotoLayout.setVerticalGroup(
            FinalPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinalPhotoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(FinalPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FPass.setText("jPasswordField1");

        jLabel2.setText("Password");

        jButton1.setText("Click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Details");

        jButton8.setText("See Friend's");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Chat \"sCool\"");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        passcheck.setForeground(new java.awt.Color(204, 0, 0));

        jMenu1.setText("Account Settings");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Update Details");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Delete Account");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Log Out");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Log Out");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Log Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(FinalName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(FinalName2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FinalJoin)
                                    .addComponent(FinalRelation)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FinalHobby)
                                    .addComponent(FinalIntrest)
                                    .addComponent(FinalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8))
                            .addComponent(FinalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinalName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FinalName2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jButton1))
                            .addComponent(passcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(FinalEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(FinalHobby)))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FinalIntrest))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(FinalRelation))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(FinalJoin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn=null;                         //Check for imports
        
       try {
           String sql="Select * from member_lps, member_lps_data, member_lps_photo where member_lps.e_mail=member_lps_data.e_mail AND member_lps.e_mail=member_lps_photo.e_mail";
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            ResultSet rs =stmt.executeQuery(sql);
            String pwd= new String( FPass.getPassword());
            String user= FinalEmail.getText();
            String name1= FinalName.getText();
            String name2= FinalName2.getText();
        String hobby= FinalHobby.getText();
        String intrest=FinalIntrest.getText();
        String relation=FinalRelation.getText();
        String join=FinalJoin.getText();
while(rs.next()){
String password =rs.getString("Password");
String email=rs.getString("E_Mail");
Blob photo=rs.getBlob("Image");
if ((pwd.equals(password)))
{
    FinalName.setVisible(true);
        FinalName2.setVisible(true);
        jLabel1.setVisible(true);
        jLabel5.setVisible(true);
        jLabel10.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        FinalEmail.setVisible(true);
        FinalHobby.setVisible(true);
        FinalIntrest.setVisible(true);
        FinalJoin.setVisible(true);
        FinalPhoto.setVisible(true);
        FinalIntrest.setVisible(true);
        FinalRelation.setVisible(true);
        jLabel2.setVisible(false);
        FPass.setVisible(false);
        passcheck.setVisible(false);
        jButton1.setVisible(false);
        jLabel3.setVisible(true);
        jButton9.setVisible(true);
        jButton8.setVisible(true);
        jMenu1.setEnabled(true);
        jMenu2.setEnabled(true);
FinalName.setText(rs.getString("First_Name"));
FinalName2.setText(rs.getString("Last_Name"));
FinalEmail.setText(rs.getString("E_Mail"));
FinalHobby.setText(rs.getString("Hobbies"));
FinalPhoto1.setText(rs.getString("Image"));
FinalIntrest.setText(rs.getString("Intrested_In"));
FinalRelation.setText(rs.getString("Relation_Status"));
FinalJoin.setText(rs.getString("Year_Of_Join"));

}
else {
    passcheck.setText("Incorrect Password!");
}
    }


    
        }
      catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String oldpass= new String(jTextField1.getPassword());
        String newpass= new String(jTextField2.getPassword());
        String confirm= new String (jTextField4.getPassword());
         try {
           String sql="Select * from member_lps";
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
             ResultSet rs =stmt.executeQuery(sql);
          while(rs.next()){   String pwd=rs.getString("Password");
            if(confirm.equals(newpass)) {if (pwd.equals(oldpass)){
                String query="UPDATE member_lps set Password='"+newpass+"'Where Password='"+oldpass+"' ";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Password Sucessfully Updated");
                jDialog2.dispose();
                rs.close();
           } else{
                        JOptionPane.showMessageDialog(null, "Incorrect Old Password");
                  
                        jDialog2.dispose(); }
            }
           else{
               JOptionPane.showMessageDialog(null, "New Passwords Do Not Match");
           }
          }
           
            
        }
         
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
         jTextField1.setText("");
         jTextField2.setText("");
         jTextField4.setText("");
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try {
           String sql="Select Password, First_Name, Last_Name, E_Mail  from member_lps";
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            ResultSet rs =stmt.executeQuery(sql);
            String pwd= new String (jTextField3.getPassword());
while(rs.next()){
String password =rs.getString("Password");
if ((pwd.equals(password)))
{
delemail.setText(rs.getString("E_Mail"));
String email=delemail.getText();
stmt=con.createStatement();
String query="Delete from member_lps WHERE E_Mail='"+ email + "' ";
String query2= "Delete From member_lps_data Where E_Mail='"+ email +"' ";
String query3= "Delete From member_lps_photo Where E_Mail='"+ email +"' ";  //Remove this Line if not running
stmt.executeUpdate(query);
stmt.executeUpdate(query2);
stmt.executeUpdate(query3); // Remove This Line If Not Running
rs.close();
JOptionPane.showMessageDialog(this, "Account Deleted");
jDialog3.dispose();
       this.dispose();
FriendsConnect mainpage= new FriendsConnect();
mainpage.setVisible(true);}
else {
    JOptionPane.showMessageDialog(this, "Incorrect Password!");
    
    jDialog3.dispose();
}

    }
    
        }
     catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       userFriend uf= new userFriend();
      uf.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:jDialog1.dispose();
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int ans=JOptionPane.showConfirmDialog(null, "<html><body>School Session is Not Working Properly On Some Systems<BR><Centre>We Are Working On it.<I> Do You Want To Continue?</I></Body></HTML>");
        if(ans==JOptionPane.YES_OPTION){
            Detail.doClick();
            Chat.setVisible(true);
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         sent.setText("Last Session Held On "+Date.getText());
        Chat.dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailActionPerformed
        // TODO add your handling code here:
        jMenu3.setText(new java.util.Date().toString());
        try {
            Class.forName("com.mysql.jdbc.Driver");
        Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");

        Statement st = c.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM  member_lps_chat_question Where E_Mail='"+FinalEmail.getText()+"';");
         DefaultTableModel mTableModel = ((DefaultTableModel) jTable2.getModel());
        Object[] rows;
        while (rs.next()) {
rows = new Object[] { rs.getString("Question"), rs.getString("RecieverE_Mail"), rs.getString("Date") };
            mTableModel.addRow(rows);
//memberTbl.addrow(rows);
          
        }
        st.close();
    }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
        //For Table3
         try {
            Class.forName("com.mysql.jdbc.Driver");
        Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");

        Statement st = c.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM  member_lps_chat_question Where RecieverE_Mail='"+FinalEmail.getText()+"';");
         DefaultTableModel mTableModel = ((DefaultTableModel) jTable3.getModel());
        Object[] rows;
        while (rs.next()) {
rows = new Object[] { rs.getString("Question"), rs.getString("Name"), rs.getString("Date"), rs.getString("E_Mail") };
            mTableModel.addRow(rows);
//memberTbl.addrow(rows);
          
        }
        st.close();
    } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
         
         //For Online Table
         try {
            Class.forName("com.mysql.jdbc.Driver");
        Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");

        Statement st = c.createStatement();
        ResultSet rs = st.executeQuery("SELECT Concat(First_Name, ' ',Last_Name)AS Name FROM  member_lps_Online Where Online='Y';");
         DefaultTableModel mTableModel = ((DefaultTableModel) jTable1.getModel());
        Object[] rows;
        while (rs.next()) {
rows = new Object[] { rs.getString("Name")};
            mTableModel.addRow(rows);
//memberTbl.addrow(rows);
          
        }
        st.close();
    }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_DetailActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jMenu3.setText(new java.util.Date().toString());
        Date.setText(new java.util.Date().toString());
        try {
            String sql="SELECT * from member_lps";
            Class.forName("com.mysql.jdbc.Driver");
        Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
String n= FinalName.getText();
String n2= FinalName2.getText();
String Name= n+n2;
        Statement st = c.createStatement();
        ResultSet rs =st.executeQuery(sql);
            String user= jTextField8.getText();
while(rs.next()){String uname=rs.getString("E_Mail");
if((user.equals (uname) || jTextField7.equals("") )){
        st.executeUpdate("Insert Into Member_lps_chat_question VALUES ('" + FinalEmail.getText() +"','" + jTextField7.getText() + "','" + jTextField8.getText() + "','" + Date.getText() +"','"+ Name +"')");
         sent.setText("Message Sent Sucessfully On "+Date.getText());
        }
else{
    sent.setText("Message Failed Recheck E-Mail/No Message To Send");
}
}
        }
        
     catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        userFinal uf= new userFinal();
        uf.setVisible(false);
        uf.dispose();
        Chat.dispose();
        int ans= JOptionPane.showConfirmDialog(null, "Do You Want to Log Out");
        if(ans==JOptionPane.YES_OPTION){
        jDialog2.dispose();
        this.dispose();
        try{
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            String onlineflag="Update member_lps_online SET Online='N' Where E_Mail='"+ FinalEmail.getText() +"' ";
            stmt.executeUpdate(onlineflag);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        FriendsConnect mainpage=new FriendsConnect();
        mainpage.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Date.setText(new java.util.Date().toString());
        int ans=JOptionPane.showConfirmDialog(this, "Clearing History Will Delete Chat Data From Both The Sides" );
        if (ans==JOptionPane.YES_OPTION){
        try {
            String sql="SELECT * from member_lps";
            Class.forName("com.mysql.jdbc.Driver");
        Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
        Statement st = c.createStatement();
        ResultSet rs=st.executeQuery(sql);
        String user= jTextField8.getText();
while(rs.next()){String uname=rs.getString("E_Mail");
        if(jTextField8.getText().equals(uname)){
        st.executeUpdate("DELETE FROM  member_lps_chat_question Where RecieverE_Mail='"+FinalEmail.getText()+"'AND E_Mail='"+jTextField8.getText()+"';");
        sent.setText("Chat History On Both Sides Deleted On"+Date.getText());
        }
        else{
            sent.setText("Enter The Friends's EMail Whose Chat is To Be Deleted/ E_Mail Not Found Check ");
        }
}
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        Date.setText(new java.util.Date().toString());
         int ans=JOptionPane.showConfirmDialog(this, "Clearing History Will Delete Chat Data From Both The Sides" );
        if (ans==JOptionPane.YES_OPTION){
        try {
            String sql="SELECT * from member_lps";
            Class.forName("com.mysql.jdbc.Driver");
        Connection c=(Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
        Statement st = c.createStatement();
        ResultSet rs=st.executeQuery(sql);
        String user= jTextField8.getText();
while(rs.next()){String uname=rs.getString("E_Mail");
        if(jTextField8.getText().equals(uname)){
        st.executeUpdate("DELETE FROM  member_lps_chat_question Where RecieverE_Mail='"+jTextField8.getText()+"'AND E_Mail='"+FinalEmail.getText()+"';");
         sent.setText("Chat History From Both Users Deleted On "+Date.getText());
        }
        else{
            sent.setText("Enter The Friends's EMail Whose Chat is To Be Deleted/ E_Mail Not Found Check ");
        }
}
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        UserUpdate update= new UserUpdate();
        update.setVisible(true); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        int ans= JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Delete Your Account?");
        if(ans==JOptionPane.YES_OPTION){
            jDialog3.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        userFinal uf= new userFinal();
        uf.dispose();
        Chat.dispose();
        int ans= JOptionPane.showConfirmDialog(null, "Do You Want to Log Out");
        if(ans==JOptionPane.YES_OPTION){
        jDialog2.dispose();
        this.dispose();
        try{
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            String onlineflag="Update member_lps_online SET Online='N' Where E_Mail='"+ FinalEmail.getText() +"' ";
            stmt.executeUpdate(onlineflag);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        FriendsConnect mainpage=new FriendsConnect();
        mainpage.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String box= (String) jComboBox2.getSelectedItem();
       if(box.equals("Show Online ON")){
            try{
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            String onlineflag="Update member_lps_online SET Online='Y' Where E_Mail='"+ FinalEmail.getText() +"' ";
            stmt.executeUpdate(onlineflag);
        }
        catch(Exception e){
            e.printStackTrace();
        }
           
       }
       
       else{
           try{
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            String onlineflag="Update member_lps_online SET Online='N' Where E_Mail='"+ FinalEmail.getText() +"' ";
            stmt.executeUpdate(onlineflag);
        }
        catch(Exception e){
            e.printStackTrace();
        }
       }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Chat;
    private javax.swing.JLabel Date;
    private javax.swing.JButton Detail;
    private javax.swing.JPasswordField FPass;
    public javax.swing.JLabel FinalEmail;
    public javax.swing.JLabel FinalHobby;
    public javax.swing.JLabel FinalIntrest;
    public javax.swing.JLabel FinalJoin;
    private javax.swing.JLabel FinalName;
    private javax.swing.JLabel FinalName2;
    private javax.swing.JPanel FinalPhoto;
    private javax.swing.JLabel FinalPhoto1;
    public javax.swing.JLabel FinalRelation;
    private javax.swing.JLabel delemail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPasswordField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    private javax.swing.JPasswordField jTextField3;
    private javax.swing.JPasswordField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel passcheck;
    private javax.swing.JLabel sent;
    // End of variables declaration//GEN-END:variables
}
