/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lpsconnect;

import DataController.DataHandleUserPage;
import com.mysql.jdbc.Connection;
import static com.sun.org.apache.xerces.internal.util.PropertyState.is;
import java.awt.Dialog;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import register.model.ForUser;

/**
 *
 * @author Sankalp
 */
public class userPage extends javax.swing.JFrame {

    /**
     * Creates new form userPage
     */
    public userPage() {
        JOptionPane.showMessageDialog(this, "Please Re-enter Password For Security Reasons On Next Window");
        initComponents();
        BtnUser.setEnabled(false);
        UserSubmitBtn.setEnabled(false);
        UserIntrest.setEditable(false);
UserRelation.setEditable(false);
UserHobby.setEditable(false);
UserName1.setVisible(false);
UserName2.setVisible(false);
UserEmail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        UserPhoto = new javax.swing.JPanel();
        UserPhoto1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserName1 = new javax.swing.JLabel();
        UserName2 = new javax.swing.JLabel();
        UserEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UserIntrest = new javax.swing.JTextField();
        UserRelation = new javax.swing.JTextField();
        UserJoin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserHobby = new javax.swing.JTextArea();
        UserSubmitBtn = new javax.swing.JButton();
        BtnUser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UserPass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        Dialog.setResizable(false);

        jLabel2.setText("ReEnter password (For Security Reasons) ");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogLayout = new javax.swing.GroupLayout(Dialog.getContentPane());
        Dialog.getContentPane().setLayout(DialogLayout);
        DialogLayout.setHorizontalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLayout.createSequentialGroup()
                .addGroup(DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogLayout.setVerticalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Details");

        UserPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UserPhoto.setToolTipText("Upload Photo");
        UserPhoto.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout UserPhotoLayout = new javax.swing.GroupLayout(UserPhoto);
        UserPhoto.setLayout(UserPhotoLayout);
        UserPhotoLayout.setHorizontalGroup(
            UserPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UserPhotoLayout.setVerticalGroup(
            UserPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        jLabel6.setText("First Name");

        jLabel7.setText("Last Name");

        jLabel8.setText("E-Mail");

        UserName1.setText("<first_name>");

        UserName2.setText("<last_name>");

        UserEmail.setText("<E_mail>");

        jLabel1.setText("Intrested In");

        jLabel5.setText("Class-Section/Alumni");

        jLabel9.setText("Hobbies");

        jLabel10.setText("Year Of Joining");

        UserIntrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIntrestActionPerformed(evt);
            }
        });

        UserHobby.setColumns(20);
        UserHobby.setRows(5);
        jScrollPane1.setViewportView(UserHobby);

        UserSubmitBtn.setText("Submit");
        UserSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSubmitBtnActionPerformed(evt);
            }
        });

        BtnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpsconnect/image/user-add-icon (2).png"))); // NOI18N
        BtnUser.setText("Upload Photo");
        BtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUserActionPerformed(evt);
            }
        });

        jButton2.setText("Click");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        UserPass.setText("jPasswordField1");

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));

        jMenu1.setText("Help");

        jMenuItem1.setText("Change Photo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UserPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserName1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(UserName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserIntrest)
                            .addComponent(UserRelation)
                            .addComponent(UserJoin)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(UserSubmitBtn)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(21, 21, 21))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(UserName1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(UserName2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(UserEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(UserIntrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UserRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(UserSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(UserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnUser)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSubmitBtnActionPerformed
/** Variable Naming Standard-
         * <page><component><orderofappear>
         * page={SignIn, Reg, User, Final}
         * component={Name, Photo, E_Mail, Photo etc}
         * orderofappear={1,2 etc} [eg-RegName1 i.e First_Name in Register Page]
         */ 
        // TODO add your handling code here:
        String name1= (UserName1.getText());
        String name2= (UserName2.getText());
        String e_mail= (UserEmail.getText());
        String intrest=(UserIntrest.getText());
        String relation=(UserRelation.getText());
        String join=(UserJoin.getText());
        String hobb=(UserHobby.getText());
        String photo=(UserPhoto1.getText());
        if(relation.equals("")||join.equals("")||intrest.equals("")||hobb.equals("")||photo == null){
            JOptionPane.showMessageDialog(this, "Details Can't Be Left Empty");
        }
        else{
        ForUser user = new ForUser(name1 ,name2 ,e_mail ,intrest, relation, join, hobb);
         try {
            int adduserdata = DataHandleUserPage.addUserData(user);
            if (adduserdata > 0) {
                JOptionPane.showMessageDialog(rootPane, "Your Information Is Sucessfully Updated");
                 JOptionPane.showMessageDialog(null, "Account Creation Sucess: Please Sign In Again To Continue!");
                FriendsConnect mainPage=new FriendsConnect();
                mainPage.setVisible(true);
         this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
        }
         UserIntrest.setText("");
         UserRelation.setText("");
         UserJoin.setText("");
         UserHobby.setText("");
         /*UserPhoto.toString();*/
        
        
        
    }//GEN-LAST:event_UserSubmitBtnActionPerformed

    private void BtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUserActionPerformed
/** Variable Naming Standard-
         * <page><component><orderofappear>
         * page={SignIn, Reg, User, Final}
         * component={Name, Photo, E_Mail, Photo etc}
         * orderofappear={1,2 etc} [eg-RegName1 i.e First_Name in Register Page]
         */ 
        // TODO add your handling code here:
        
       JFileChooser fc=new JFileChooser(); 
       fc.showOpenDialog(this); 
       File f=fc.getSelectedFile(); 
       String path=f.getAbsolutePath(); 
       UserPhoto1.setIcon(new ImageIcon(path));
      {
       try{ FileInputStream fin=new FileInputStream(f); 
       int len=(int)f.length(); 
       Class.forName("com.mysql.jdbc.Driver");
        Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
        PreparedStatement ps=connection.prepareStatement("insert into `member_lps_photo` values('" + UserEmail.getText() + "', ?)");
       ps.setBinaryStream(1, fin, len); 
       int status=ps.executeUpdate();
       if(status>0) 
       { JOptionPane.showMessageDialog(null, "Successfully inserted"); 
       }
       else{showMessageDialog(null, "Image not inserted!");
       }
       }catch(Exception e){e.printStackTrace(); }
       }
    }//GEN-LAST:event_BtnUserActionPerformed

    private void UserIntrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIntrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIntrestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        
        try {
           String sql="Select Password, First_Name, Last_Name, E_Mail  from member_lps";
            Class.forName ("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
            Statement stmt=con.createStatement();
            ResultSet rs =stmt.executeQuery(sql);
            String pwd= new String (UserPass.getPassword());
while(rs.next()){
String password =rs.getString("Password");
if ((pwd.equals(password)))
{UserIntrest.setEditable(true);
UserRelation.setEditable(true);
UserHobby.setEditable(true);
UserName1.setVisible(true);
UserName2.setVisible(true);
UserEmail.setVisible(true);
BtnUser.setEnabled(true);
UserSubmitBtn.setEnabled(true);
UserIntrest.setEditable(true);
 UserPass.setVisible(false);
 jLabel12.setVisible(false);
        jButton2.setVisible(false);
UserName1.setText(rs.getString("First_Name"));
UserName2.setText(rs.getString("Last_Name"));
UserEmail.setText(rs.getString("E_Mail"));}
else {
    jLabel12.setText( "Incorrect Password!");
}
    }
    
        }
     catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Internet Connection");
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        UserPhoto1.setText("");
       try{
       Class.forName("com.mysql.jdbc.Driver");
        Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6100273", "sql6100273", "sgTCHQBbhD");
          {
           String sql="Select password from member_lps";
           
            Statement stmt=connection.createStatement();
            ResultSet rs =stmt.executeQuery(sql);
            String pwd= UserPass.getText();
while(rs.next()){
String password =rs.getString("Password");
if(pwd.equals(password))
    JOptionPane.showMessageDialog(this, "Image Cannot be Deleted Application Failiure");
else {
    JOptionPane.showMessageDialog(this, "Please Enter Password First!!");
}
    }
    
        }
          
       }catch(Exception e){System.out.println(e); }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnUser;
    private javax.swing.JFrame Dialog;
    public javax.swing.JLabel UserEmail;
    public javax.swing.JTextArea UserHobby;
    public javax.swing.JTextField UserIntrest;
    public javax.swing.JTextField UserJoin;
    public javax.swing.JLabel UserName1;
    public javax.swing.JLabel UserName2;
    private javax.swing.JPasswordField UserPass;
    public javax.swing.JPanel UserPhoto;
    private javax.swing.JLabel UserPhoto1;
    public javax.swing.JTextField UserRelation;
    public javax.swing.JButton UserSubmitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
